name: Commit

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main

# permissions:
#   actions: write
#   checks: write
#   contents: write
#   pages: write
#   id-token: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: build and commit
        if: "!contains(github.event.head_commit.message, ':robot:')"
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
        run: ./commit.sh
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.generate.outputs.token }}
          repository: kijimaD/roam-ui
          event-type: publish
