name: Publish org-roam-ui page

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main

permissions:
  actions: write
  checks: write
  contents: write
  pages: write
  id-token: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: build and commit
        if: "!contains(github.event.head_commit.message, ':robot:')"
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGE }}
        run: ./commit.sh

  main:
    needs:
      - commit
    runs-on: ubuntu-latest
    steps:
      - name: Generate org-roam-ui page
        uses: ikoamu/org-roam-ui-hosting@main
        with:
          deploy-to-pages: true
          org-roam-directory: pages
          org-roam-db-filename: org-roam.db
